# Generated by Django 3.1.4 on 2020-12-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=100)),
                ('semester', models.IntegerField(db_column='Semester')),
                ('hours_per_week', models.FloatField(db_column='Hours_per_week')),
                ('program', models.CharField(db_column='Program', max_length=10)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=2, primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='Type_Name', max_length=10)),
            ],
            options={
                'db_table': 'course_type',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='ExamInformation',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=3, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_column='Year')),
                ('type', models.CharField(db_column='Type', max_length=10)),
            ],
            options={
                'db_table': 'exam_information',
            },
        ),
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=1, primary_key=True, serialize=False)),
                ('full_marks', models.IntegerField(db_column='Full_Marks')),
                ('pass_marks', models.IntegerField(db_column='Pass_Marks')),
                ('duration', models.FloatField(db_column='Duration')),
            ],
            options={
                'db_table': 'marking_scheme',
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('paper_link', models.TextField(blank=True, db_column='Paper_link', null=True)),
                ('course', models.ForeignKey(db_column='Course_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionBankIOE.course')),
                ('exam', models.ForeignKey(db_column='Exam_Id', on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionBankIOE.examinformation')),
            ],
            options={
                'db_table': 'question_paper',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='depart_code',
            field=models.ForeignKey(db_column='Depart_Code', on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionBankIOE.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='marks_code',
            field=models.ForeignKey(db_column='Marks_Code', on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionBankIOE.markingscheme'),
        ),
        migrations.AddField(
            model_name='course',
            name='type_code',
            field=models.ForeignKey(db_column='Type_Code', on_delete=django.db.models.deletion.DO_NOTHING, to='QuestionBankIOE.coursetype'),
        ),
    ]
